jenkins:
  systemMessage: "Jenkins as Code"
  views:
    - list:
        includeRegex: ".*"
        name: "All"
    - list:
        includeRegex: "Stage.*"
        name: "Stages"
    - list:
        includeRegex: ".*test.*"
        name: "Tests"

tool:
  allure:
    installations:
    - name: "Allure"
      properties:
      - installSource:
          installers:
          - allureCommandlineInstaller:
              id: "2.13.0"

unclassified:
  simple-theme-plugin:
    elements:
    - cssUrl:
        url: "https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-teal.css"
  globalLibraries:
    libraries:
    - defaultVersion: "master"
      name: "lib_name"
      retriever:
        modernSCM:
          scm:
            git:
              remote: "https://github.com/d-shch/jenkins-as-code.git"
              traits:
              - "gitHubBranchDiscovery"

jobs:
  - script: >
      pipelineJob('DeployJenkins') {
        triggers {
          scm('* * * * *')
        }
        definition {
          cps {
            script("""\
              node('master') {
                deleteDir()
                stage('Deploy Jenkins') {
                  git(url: 'https://github.com/d-shch/jenkins-as-code.git', 
                    branch: 'master')
                  sh(label: 'Update Jobs via JJB', 
                    script: '''
                      jenkins-jobs --ignore-cache --log_level debug --conf jenkins_jobs.ini update jobs
                    ''')
                  sh(label: 'Update plugins', 
                    script: '''
                      wget http://localhost:8080/jnlpJars/jenkins-cli.jar
                      java -jar jenkins-cli.jar -s http://localhost:8080/ install-plugin `cat plugins.txt`
                    ''')
                  sh(label: 'Update Jenkins config', 
                    script: '''
                      rm /usr/share/jenkins/jenkins.yaml
                      cp jenkins.yaml /usr/share/jenkins/jenkins.yaml
                      curl -X POST localhost:8080/configuration-as-code/reload
                    ''')
                }
              }""".stripIndent())
          }
        }
      }